### ISSUE TITLE
ACO error: Permission Denied

### ISSUE THREAD

**Issue by franperezg** [SAP-samples/tier2-rfc-proxy#1]
Hi Andre, good afternoon, excellent Blog!
I am writing to inform you of an issue I have encountered while implementing the Tier 2 RFC Proxy Generator in a v2023 Private Cloud Environment.

I was able to perform a pull of the repository in my system and added the required notes. However, when I ran the report in the GUI with the corresponding parameters, I received the following error: 
`'Exception Occurred Generating Objects: ACO error: Permission Denied.'`

Could you please advise on how to resolve this issue? If there is a solution, we would be grateful if you could provide it.
Thank you in advance.

**Comment by arafya** [comment]
Hi @franperezg,
We encountered the same error message. After investigation, we found that our target package was Typed "Main package". It worked when we put a Development Package as Target. 
Looks like we can't generate objects on Main Packages...
Hope this will help you resolve your issue.

**Comment by anfisc** [comment]
I fixed this. The report now checks whether the package is of type development.
